name: Deploy File List to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate file list
      run: |
        echo "<!DOCTYPE html><html lang='en'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width, initial-scale=1.0'><title>File List</title></head><body><h1>Files in Repository</h1><ul>" > index.html
        for file in $(git ls-files); do
          echo "<li>$file</li>" >> index.html
        done
        echo "</ul></body></html>" >> index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
